from fastapi import FastAPI, HTTPException, Query
from fastapi.responses import StreamingResponse
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import Any, AsyncIterator, Dict, List, Optional
import json
import asyncio
import api as llm_api
import os
import dotenv

dotenv.load_dotenv()  

app = FastAPI(title="Hallucinate.me Mock API")

# Настройка CORS
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # В продакшене указать конкретные домены
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


class ChatMessage(BaseModel):
    """Модель сообщения чата"""
    role: str  # "system", "user", "assistant"
    content: str


class ChatRequest(BaseModel):
    """Модель запроса для чата"""
    history: List[ChatMessage]  # История чата
    message: str  # Новое сообщение пользователя
    temperature: Optional[float] = 0.7  # Температура генерации
    max_tokens: Optional[int] = None  # Максимальное количество токенов


def generate_mock_response(user_message: str) -> str:
    """
    Генерирует mock ответ на основе сообщения пользователя
    
    Args:
        user_message: Сообщение пользователя
        
    Returns:
        Mock ответ
    """
    # Простые шаблоны ответов для разных типов запросов
    message_lower = user_message.lower()
    
    if any(word in message_lower for word in ["hello", "hi", "привет"]):
        return "Hello! I'm a mock LLM assistant. How can I help you today?"
    elif any(word in message_lower for word in ["code", "programming", "код"]):
        return "Here's a simple example:\n\n```python\nprint('Hello, World!')\n```\n\nThis is a mock response. In production, this would be generated by a real LLM."
    elif any(word in message_lower for word in ["math", "calculate", "математика"]):
        return "Let me help you with that calculation. This is a mock response, but in production I would solve your math problem step by step."
    elif "?" in user_message:
        return f"That's an interesting question about '{user_message[:50]}...'. This is a mock response, but in production I would provide a detailed answer."
    else:
        return f"I understand you're asking about: {user_message[:100]}. This is a mock response from the mock API. In production, this would be a real AI-generated response based on your message."


@app.get("/")
async def root():
    """Проверка работоспособности API"""
    return {"status": "ok", "message": "Hallucinate.me Mock API is running"}


@app.post("/api/chat/stream")
async def chat_stream(request: ChatRequest):
    llm_client = llm_api.LLM(
        model="openrouter/polaris-alpha",
        api_key=os.getenv("OPENAI_API_KEY"),
        base_url=os.getenv("OPENAI_URL"),
    )

    history_dicts = [msg.model_dump() for msg in request.history]

    def generator():
        try:
            for chunk in llm_client.chat_stream(
                history_dicts,
                llm_api.Message(request.message),
                request.temperature,
                request.max_tokens
            ):
                # Отправляем в формате SSE с JSON
                data = json.dumps({"content": chunk}, ensure_ascii=False)
                yield f"data: {data}\n\n"
        except Exception as e:
            error_data = json.dumps({"error": str(e)}, ensure_ascii=False)
            yield f"data: {error_data}\n\n"
        finally:
            # Закрывающий маркер
            yield "data: [DONE]\n\n"

    return StreamingResponse(
        generator(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "X-Accel-Buffering": "no",
        },
    )


@app.post("/api/chat")
async def chat(request: ChatRequest):
    """
    Эндпоинт для получения полного ответа от LLM (без стриминга, mock версия)
    
    Принимает:
    - history: список сообщений в формате [{"role": "user", "content": "..."}]
    - message: новое сообщение пользователя
    - temperature: температура генерации (опционально)
    - max_tokens: максимальное количество токенов (опционально)
    
    Возвращает: полный текст ответа
    """
    try:
        # Генерируем mock ответ
        mock_response = generate_mock_response(request.message)
        
        # Имитируем небольшую задержку обработки
        await asyncio.sleep(0.1)
        
        return {"response": mock_response}
        
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Ошибка при обработке запроса: {str(e)}")


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=3001)

