from fastapi import FastAPI, HTTPException
from fastapi.responses import StreamingResponse
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import List, Optional
import json
import asyncio

app = FastAPI(title="Hallucinate.me Mock API")

# Настройка CORS
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # В продакшене указать конкретные домены
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


class ChatMessage(BaseModel):
    """Модель сообщения чата"""
    role: str  # "system", "user", "assistant"
    content: str


class ChatRequest(BaseModel):
    """Модель запроса для чата"""
    history: List[ChatMessage]  # История чата
    message: str  # Новое сообщение пользователя
    temperature: Optional[float] = 0.7  # Температура генерации
    max_tokens: Optional[int] = None  # Максимальное количество токенов


def generate_mock_response(user_message: str) -> str:
    """
    Генерирует mock ответ на основе сообщения пользователя
    
    Args:
        user_message: Сообщение пользователя
        
    Returns:
        Mock ответ
    """
    # Простые шаблоны ответов для разных типов запросов
    message_lower = user_message.lower()
    
    if any(word in message_lower for word in ["hello", "hi", "привет"]):
        return "Hello! I'm a mock LLM assistant. How can I help you today?"
    elif any(word in message_lower for word in ["code", "programming", "код"]):
        return "Here's a simple example:\n\n```python\nprint('Hello, World!')\n```\n\nThis is a mock response. In production, this would be generated by a real LLM."
    elif any(word in message_lower for word in ["math", "calculate", "математика"]):
        return "Let me help you with that calculation. This is a mock response, but in production I would solve your math problem step by step."
    elif "?" in user_message:
        return f"That's an interesting question about '{user_message[:50]}...'. This is a mock response, but in production I would provide a detailed answer."
    else:
        return f"I understand you're asking about: {user_message[:100]}. This is a mock response from the mock API. In production, this would be a real AI-generated response based on your message."


@app.get("/")
async def root():
    """Проверка работоспособности API"""
    return {"status": "ok", "message": "Hallucinate.me Mock API is running"}


@app.post("/api/chat/stream")
async def chat_stream(request: ChatRequest):
    """
    Эндпоинт для получения ответа от LLM стримом (mock версия)
    
    Принимает:
    - history: список сообщений в формате [{"role": "user", "content": "..."}]
    - message: новое сообщение пользователя
    - temperature: температура генерации (опционально)
    - max_tokens: максимальное количество токенов (опционально)
    
    Возвращает: стрим текста ответа
    """
    try:
        # Генерируем mock ответ
        mock_response = generate_mock_response(request.message)
        
        def generate():
            """Генератор для стриминга ответа"""
            try:
                # Разбиваем ответ на слова для имитации стриминга
                words = mock_response.split(' ')
                
                for i, word in enumerate(words):
                    # Добавляем пробел перед словом (кроме первого)
                    chunk = (' ' if i > 0 else '') + word
                    
                    # Отправляем chunk в формате Server-Sent Events
                    yield f"data: {json.dumps({'content': chunk}, ensure_ascii=False)}\n\n"
                    
                    # Имитируем задержку для реалистичного стриминга
                    # Note: В генераторе используем time.sleep, так как это синхронный генератор
                    import time
                    time.sleep(0.05)  # 50ms задержка между словами
                
                # Отправляем сигнал завершения
                yield "data: [DONE]\n\n"
            except Exception as e:
                error_data = json.dumps({"error": str(e)}, ensure_ascii=False)
                yield f"data: {error_data}\n\n"
        
        return StreamingResponse(
            generate(),
            media_type="text/event-stream",
            headers={
                "Cache-Control": "no-cache",
                "Connection": "keep-alive",
            }
        )
        
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Ошибка при обработке запроса: {str(e)}")


@app.post("/api/chat")
async def chat(request: ChatRequest):
    """
    Эндпоинт для получения полного ответа от LLM (без стриминга, mock версия)
    
    Принимает:
    - history: список сообщений в формате [{"role": "user", "content": "..."}]
    - message: новое сообщение пользователя
    - temperature: температура генерации (опционально)
    - max_tokens: максимальное количество токенов (опционально)
    
    Возвращает: полный текст ответа
    """
    try:
        # Генерируем mock ответ
        mock_response = generate_mock_response(request.message)
        
        # Имитируем небольшую задержку обработки
        await asyncio.sleep(0.1)
        
        return {"response": mock_response}
        
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Ошибка при обработке запроса: {str(e)}")


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=3001)

